apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmu-dummy
  labels:
    app: pmu-dummy
spec:
  selector:
    matchLabels:
      app: pmu-dummy
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: pmu-dummy
    spec:
      containers:
        - name: pmu-dummy
          image: registry.git-ce.rwth-aachen.de/acs/private/research/platone/wp2/pmu-dummy:latest
          env:
            #Config for both MQTT and Kafka
            - name: JSON_TEMPLATE
              value: device_template.json #path for the data template file
            - name: PRODUCER_TYPE
              value: kafka #"mqtt" or "kafka"
            - name: BROKER_URL
              value: strimzi-cluster-kafka-bootstrap.demo #FQDN or IP
            - name: BROKER_PORT
              value: "9092"
            - name: TOPIC_NAME
              value: pmu-dummy-in
            #MQTT Specific Config
            - name: MQTT_USER
              value: admin #USERNAME
            - name: MQTT_PWD
              value: admin #PASSWORD
            - name: MQTT_SSL 
              value: "false" #toggle ssl true/false
            - name: MQTT_CAFILE
              value: "/etc/ssl/certs/DST_Root_CA_X3.pem" #example ca file for let's Encrypt
            - name: MQTT_DEVICE_NAME
              value: device1-dummy
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
