apiVersion: apps/v1
kind: Deployment
metadata:
  name: kstreams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstreams
  template:
    metadata:
      labels:
        app: kstreams
    spec:
      containers:
        - name: kstreams
          image: registry.git-ce.rwth-aachen.de/acs/private/research/platone/wp2/pmu-streams-connector:latest
          env:
            - name: KAFKA_BROKER
              value: strimzi-cluster-kafka-bootstrap.demo:9092
            - name: INPUT_TOPIC
              value: pmu-dummy-in
            - name: OUTPUT_TOPIC
              value: pmu-dummy-out
            - name: APP_ID
              value: pmu-dummy-app
      imagePullSecrets:
        - name: regcred
